/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tokuhirom' at '5/27/15 10:42 AM' with Gradle 2.4
 *
 * @author tokuhirom, @date 5/27/15 10:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
